### ISSUE TITLE
Run in Sails

### ISSUE THREAD

**Issue by tru3d3v** [mbejda/Node-OpenNLP#1]
Hello mbejda,

This library can run in sailsjs ?.

Advice me please :)

**Comment by mbejda** [comment]
I have not worked with sailsjs so I'm not sure. The library conveniently includes some basic models so it should work fine out of the box. I would imagine that all you would need is to have node-java properly configured in your sailsjs application.

**Comment by tru3d3v** [comment]
is node-java  run  jdk8 64 bit ?

**Comment by mbejda** [comment]
I'm not sure your going to do research around Java.
