### ISSUE TITLE
nameFinder returns empty array

### ISSUE THREAD

**Issue by franciskim** [mbejda/Node-OpenNLP#2]
Hi there - first off, great work on the code.

I have everything running well with results being displayed however nameFinder gives me an empty array every time. Is it because there are no recognised names in what I'm inputting?

**Comment by mbejda** [comment]
>  Is it because there are no recognized names in what I'm inputting?

Possibly. Please post the sentence your using here.

Is this example working for you?

```
var sentence = 'Pierre Vinken , 61 years old , will join the board as a nonexecutive director Nov. 29 .';
var nameFinder = new openNLP().nameFinder;
nameFinder.find(sentence, function(err, results) {
    console.log(results)
});
```

**Comment by hussainb** [comment]
Hello, same issue here, am on a windows 7 x64 OS, name finder returns `[{}]` with your example sentence. the err parameter is undefined, so not an error.

**Comment by mbejda** [comment]
@hussainb @franciskim  Ok i think I know whats going on. Java is returning its own dataType. You can do `console.log(results.toString())` on the results and you ll get your response your looking for.

**Comment by hussainb** [comment]
@mbejda , Yes, doing .toString() works, I now get `[0..2) person` in the console. I thought I might get the words "Pierre Vinken". or I might have to read the openNLP docs.

**Comment by franciskim** [comment]
Strange, I thought I had not changed anything - but it is working now, even without `.toString()` I must have reinstalled nodejs on my Mac OS X, perhaps a version mismatch? Closing the issue.

**Comment by pvlreyes** [comment]
Hello @mbejda,  i'm having the same issue as @hussainb. same windows version, same result for with and without toString(). Any solutions on this?
