### ISSUE TITLE
node v4.0

### ISSUE THREAD

**Issue by jloveric** [mbejda/Node-OpenNLP#4]
Has anyone installed this with node v4.0?  There is a branch of node-java that has recently been fixed to work with node v4 https://github.com/joeferner/node-java/issues/250 so most likely the version of node-java used in node-opennlp will need to be upgraded as well.

**Comment by jloveric** [comment]
Ok, answering my own question, changing the dependencies in package.json so that we have "java": "https://github.com/joeferner/node-java.git#upgrade-nan-to-2" allowed the module to be built.

**Comment by mbejda** [comment]
Awesome :) Happy it worked for you. I'll try to submit a fix later this week.

**Comment by thuykaka** [comment]
dear mbejda.
i have a problem with name finder person.
My code:
var openNLP = require("opennlp");
var sentence = 'John is good';
var nameFinder = new openNLP().nameFinder;
    nameFinder.find(sentence, function(err, results) {  
            console.log(results)  
    });
It return [{}].why?i think it is [{John}]

**Comment by mbejda** [comment]
@thuykaka  Have you tried `results.toString()`

**Comment by thuykaka** [comment]
It's return [0..1) person.Can you help me?

**Comment by mbejda** [comment]
@thuykaka that is correct response from OpenNLP itself. It returns you the location of where the person(s) is located in the sentence. For example : 

```
var openNLP = require("opennlp");
var sentence = 'John and Tom is awesome.';
var nameFinder = new openNLP().nameFinder;
nameFinder.find(sentence, function(err, results) {

  console.log(results.toString())
});
```

will yield :

```
[0..1) person,[2..3) person
```

How you decide to parse the response is upto you.

**Comment by thuykaka** [comment]
@mbejda tks

**Comment by mbejda** [comment]
updated all the package dependencies in sha f409cdcb68aa9485cf2382dff0a369053387e51b. All tests are passing. Closing issue.
