### ISSUE TITLE
Name Finder Can't Find Barack Obama

### ISSUE THREAD

**Issue by micah-williamson** [mbejda/Node-OpenNLP#7]
Can you shed some light on how this works? It detects Sam Jones as a name but not Barack Obama. Using the `nameDetector` example I changed the sample string to:

```
var sentence = 'Pierre Vinken , 61 years old , will join the board as a nonexecutive director Nov. 29. Barack Obama made a sandwich.';
```

This returns `[0..2) person` showing it found Pierre Vinken as a person. Changing Barack Obama to Sam Jones I get this result:

```
var sentence = 'Pierre Vinken , 61 years old , will join the board as a nonexecutive director Nov. 29. Sam Jones made a sandwich.';

[0..2) person,[17..19) person
```

But Barack Obama can be found if the string is trimmed to just:

```
var sentence = 'Barack Obama made a sandwich.';
```

I don't expect this behavior. Any ideas?

**Comment by mbejda** [comment]
Are you using your own trained dataset or are you using the default one?

**Comment by micah-williamson** [comment]
I'm using the default one. I don't have the data to build my own dataset so I was hoping to get a "pretty good" one freely available.

**Comment by mbejda** [comment]
I believe I have identified the issue and a fix will be pushed in a few minutes.

**Comment by mbejda** [comment]
@iamchairs The fix has been published to the npm. 

```
var sentence = 'Pierre Vinken , 61 years old , will join the board as a nonexecutive director Nov. 29. Barack Obama made a sandwich.';
var tokenizer = new openNLP().tokenizer;

    var nameFinder = new openNLP().nameFinder;
    nameFinder.find(sentence, function(err, tokens_arr) {
        console.log(err, tokens_arr)

    });
```

Now gives me `'[0..2) person,[18..20) person'`.

**Comment by micah-williamson** [comment]
Wow that was a fast response! Thanks!
