### ISSUE TITLE
Error while installing it

### ISSUE THREAD

**Issue by sourabh1007** [mbejda/Node-OpenNLP#9]
I getting following error while installing the package:

node_modules\nan\nan.h(590): error C2039: 'GCEpilogueCallback': is not a member of 'v8::Isolate' (compiling source file ..\src\java.cpp)
node_modules\nan\nan.h(590): error C2039: 'GCEpilogueCallback': is not a member of 'v8::Isolate' (compiling source file ..\src\n
odeJavaBridge.cpp)

so on..

I have updated the nan package to 2.5.0. Does this package work with java 8? because it looks like this error is coming up when it tries to install java 6 as dependent package. Need your help in solving this issue. Any lead will be appreciated. Thanks in advance.

**Comment by mbejda** [comment]
The issue is caused by the Node-Java version.
https://github.com/mbejda/Node-OpenNLP/blob/master/package.json#L30
My guess is that it is not be compatible with your current Node version. I came across a similar issue when I updated my Node.

**Comment by sourabh1007** [comment]
Yes, you are right. My current  node version is v7.2.1 and I am able to install Java 8 successfully. But when I am trying to install java 6 it is throwing above error. and opennlp package uses java 6. So I have 2 Questions:
1. How can I know which node version supports java 6?
2. How can I reduce the node version? Do I need to uninstall the current version and install the older version?

**Comment by sourabh1007** [comment]
and one more question, will_opennlp_ library use latest version of java and node in future? Do you have any plan to release it with latest versions of node and java?

**Comment by mbejda** [comment]
> How can I know which node version supports java 6?

https://github.com/joeferner/node-java

> How can I reduce the node version? Do I need to uninstall the current version and install the older version?

I suggest you use `nvm` to change between node versions easily. 
https://github.com/creationix/nvm

> will_opennlp_ library use latest version of java and node in future? Do you have any plan to release it with latest versions of node and java?

I do have plans on making `Node-OpenNLP` to work with the latest Node and Node-Java sometimes around January/February.

**Comment by sourabh1007** [comment]
Thanks a lot for your help :)

**Comment by bogas04** [comment]
I've created a fork of this project which uses latest version of node-java, and also adds better error handling. I intend to add promise support to it as well.

https://www.npmjs.com/package/node-opennlp
